export {
  DEFAULT_CUSTOM_SIDEBAR_TITLEBAR_FOREGROUND_COLOR,
  DEFAULT_CUSTOM_SIDEBAR_TITLEBAR_DARK_FOREGROUND_COLOR,
  DEFAULT_CUSTOM_SIDEBAR_TITLEBAR_BACKGROUND_COLOR,
  DEFAULT_CUSTOM_SIDEBAR_TITLEBAR_BACKGROUND_TINT_COLOR,
  DEFAULT_CUSTOM_SIDEBAR_TITLEBAR_BACKGROUND_DARKNESS_PERCENT,
  MIN_CUSTOM_SIDEBAR_TITLEBAR_BACKGROUND_DARKNESS_PERCENT,
  MAX_CUSTOM_SIDEBAR_TITLEBAR_BACKGROUND_DARKNESS_PERCENT,
  clampSidebarTitlebarBackgroundDarknessPercent,
  getSidebarTitlebarBackgroundForDarkness,
  getSidebarTitlebarForegroundForBackground,
  type SidebarTitlebarGradientColors,
  getSidebarTitlebarGradientColors,
  getAccentColorForBackgroundTint,
  DEFAULT_CUSTOM_SIDEBAR_TITLEBAR_LIGHT_BACKGROUND_COLOR,
  DEFAULT_CUSTOM_SIDEBAR_TITLEBAR_LIGHT_BACKGROUND_TINT_COLOR,
  DEFAULT_CUSTOM_SIDEBAR_TITLEBAR_LIGHT_BACKGROUND_LIGHTNESS_PERCENT,
  MIN_CUSTOM_SIDEBAR_TITLEBAR_LIGHT_BACKGROUND_LIGHTNESS_PERCENT,
  MAX_CUSTOM_SIDEBAR_TITLEBAR_LIGHT_BACKGROUND_LIGHTNESS_PERCENT,
  clampSidebarTitlebarLightBackgroundLightnessPercent,
  getSidebarTitlebarLightBackgroundForLightness,
  type DarkThemePreset,
  type LightThemePreset,
  type DarkChromeControls,
  type LightChromeControls,
  DEFAULT_DARK_THEME_PRESET,
  DEFAULT_LIGHT_THEME_PRESET,
  DARK_THEME_PRESET_CONTROLS,
  LIGHT_THEME_PRESET_CONTROLS,
  normalizeDarkThemePreset,
  normalizeLightThemePreset,
  resolveDarkChromeControls,
  resolveLightChromeControls,
  THEME_CONTRAST_MIN_POINTS,
  THEME_CONTRAST_MAX_POINTS,
  clampThemeContrastPoints,
  readThemeContrastPoints,
  getWorkAreaBackgroundForSettings,
  presetDarknessWithContrast,
  presetLightnessWithContrast,
  getAccentColorForSettings,
  getLightAccentColorForBackgroundTint,
  getLightAccentColorForSettings,
  getSidebarTitlebarBackgroundForVariant,
  getSidebarTitlebarMenuBackgroundForChrome,
  getSessionChatBackgroundForChrome,
} from './ghostex-settings/titlebar-color';
export {
  type DiagnosticLoggingScenarioId,
  type DiagnosticLoggingScenarioState,
  type DiagnosticLoggingSettings,
  type DiagnosticLoggingScenarioGroup,
  type DiagnosticLoggingScenarioDefinition,
  DIAGNOSTIC_LOGGING_SCENARIOS,
  isDiagnosticLoggingScenarioEnabled,
  setDiagnosticLoggingScenario,
  areDiagnosticLoggingSettingsEqual,
  normalizeDiagnosticLoggingSettings,
} from './ghostex-settings/diagnostic-logging';
export {
  type GhosttyConfirmCloseSurface,
  type GhosttyCopyOnSelect,
  type GhosttyScrollbar,
  type TerminalCursorStyle,
  type TerminalBackgroundImageFit,
  type TerminalViewWidthMode,
  type PortlessProtocol,
  type WebLinkOpenTarget,
  type ChatFileOpenView,
  type DefaultEditorCommand,
  type CommandsPanelSide,
  type WindowGlassMode,
  type WindowGlassSource,
  type WindowGlassImagePlacement,
  type PanelAnimationSpeed,
  type SidebarSpaceSwitchBehavior,
  type SidebarVisibilityMemory,
  MIN_SIDEBAR_COLLAPSE_ANIMATION_DURATION_MS,
  MAX_SIDEBAR_COLLAPSE_ANIMATION_DURATION_MS,
  SIDEBAR_COLLAPSE_ANIMATION_DURATION_STEP_MS,
  DEFAULT_SIDEBAR_COLLAPSE_ANIMATION_DURATION_MS,
  MIN_SIDEBAR_TOOLTIP_DELAY_MS,
  MAX_SIDEBAR_TOOLTIP_DELAY_MS,
  SIDEBAR_TOOLTIP_DELAY_STEP_MS,
  DEFAULT_SIDEBAR_TOOLTIP_DELAY_MS,
  MIN_SESSION_CHAT_ZOOM_PERCENT,
  MAX_SESSION_CHAT_ZOOM_PERCENT,
  SESSION_CHAT_ZOOM_PERCENT_STEP,
  DEFAULT_SESSION_CHAT_ZOOM_PERCENT,
  clampSessionChatZoomPercent,
  MIN_WINDOW_GLASS_SIDEBAR_OPACITY_PERCENT,
  MAX_WINDOW_GLASS_SIDEBAR_OPACITY_PERCENT,
  MIN_WINDOW_GLASS_WORK_AREA_TINT_PERCENT,
  MAX_WINDOW_GLASS_WORK_AREA_TINT_PERCENT,
  DEFAULT_WINDOW_GLASS_SIDEBAR_OPACITY_DARK_PERCENT,
  DEFAULT_WINDOW_GLASS_SIDEBAR_OPACITY_LIGHT_PERCENT,
  DEFAULT_WINDOW_GLASS_WORK_AREA_TINT_DARK_PERCENT,
  DEFAULT_WINDOW_GLASS_WORK_AREA_TINT_LIGHT_PERCENT,
  clampWindowGlassSidebarOpacityPercent,
  clampWindowGlassWorkAreaTintPercent,
  migrateWindowGlassWorkAreaTintPercent,
  MIN_SESSION_CHAT_TRANSCRIPT_WIDTH_PERCENT,
  MAX_SESSION_CHAT_TRANSCRIPT_WIDTH_PERCENT,
  SESSION_CHAT_TRANSCRIPT_WIDTH_PERCENT_STEP,
  DEFAULT_SESSION_CHAT_TRANSCRIPT_WIDTH_PERCENT,
  clampSessionChatTranscriptWidthPercent,
  MIN_TERMINAL_VIEW_WIDTH_PERCENT,
  MAX_TERMINAL_VIEW_WIDTH_PERCENT,
  TERMINAL_VIEW_WIDTH_PERCENT_STEP,
  DEFAULT_TERMINAL_VIEW_WIDTH_PERCENT,
  DEFAULT_TERMINAL_VIEW_WIDTH_MODE,
  TERMINAL_VIEW_WIDTH_MODE_OPTIONS,
  clampTerminalViewWidthPercent,
  clampSidebarCollapseAnimationDurationMs,
  clampSidebarTooltipDelayMs,
  type PreferredAgentInterface,
  type SidebarSettingsPresetId,
  type PromptEditorBackend,
  type SessionTitleGenerationAgent,
  type AppShotsHotkey,
  type KeepAwakeDurationMinutes,
  type AutoSleepIdleMinutes,
  DEFAULT_TERMINAL_PANE_HORIZONTAL_PADDING_PX,
  DEFAULT_TERMINAL_PANE_PADDING_PX,
  MIN_TERMINAL_PANE_PADDING_PX,
  MAX_TERMINAL_PANE_PADDING_PX,
  MIN_COMMANDS_PANEL_DEFAULT_HEIGHT_PX,
  MAX_COMMANDS_PANEL_DEFAULT_HEIGHT_PX,
  DEFAULT_SIDEBAR_DEFAULT_WIDTH_PX,
  MIN_SIDEBAR_DEFAULT_WIDTH_PX,
  MAX_SIDEBAR_DEFAULT_WIDTH_PX,
  DEFAULT_PROJECT_SWITCH_KEEP_ALIVE_MINUTES,
  MIN_PROJECT_SWITCH_KEEP_ALIVE_MINUTES,
  MAX_PROJECT_SWITCH_KEEP_ALIVE_MINUTES,
  DEFAULT_PROJECT_SESSION_LIST_COLLAPSED_COUNT,
  MIN_PROJECT_SESSION_LIST_COLLAPSED_COUNT,
  MAX_PROJECT_SESSION_LIST_COLLAPSED_COUNT,
  clampCommandsPanelDefaultHeightPx,
  clampSidebarDefaultWidthPx,
  clampProjectSwitchKeepAliveMinutes,
  clampProjectSessionListCollapsedCount,
  clampTerminalPanePaddingPx,
  type ghostexSettings,
  type ghostexSettingsPatch,
  type ghostexSettingsUpdateSource,
  canSettingsUpdateSourceChangeRemoteMachines,
  SIDEBAR_SETTINGS_PRESET_KEYS,
  type SidebarSettingsPresetKey,
  type SidebarSettingsPresetSettings,
} from './ghostex-settings/types';
export {
  SIDEBAR_SETTINGS_PRESET_SETTINGS,
  SIDEBAR_SETTINGS_PRESETS,
  getSidebarSettingsPresetId,
} from './ghostex-settings/presets';
export { DEFAULT_ghostex_SETTINGS } from './ghostex-settings/defaults';
export {
  CUSTOM_VIEW_ID_PREFIX,
  normalizeCustomViewUrl,
  normalizeGhostexCustomViews,
  type GhostexCustomView,
} from './ghostex-settings/custom-views';
export {
  DEFAULT_GHOSTEX_VIEW_SCOPE,
  extensionViewScopeKey,
  ghostexViewScope,
  isDefaultGhostexViewScope,
  isViewScopeVisible,
  normalizeGhostexViewScope,
  normalizeGhostexViewScopes,
  officialViewScopeKey,
  parseViewScopeSpaceKey,
  prunedGhostexViewScope,
  resolveViewScopeState,
  setGhostexViewScope,
  setViewScopeOverride,
  viewScopeDescription,
  viewScopeSpaceKey,
  withViewScopeOverride,
  type GhostexViewScope,
  type GhostexViewScopeOverrideTarget,
  type GhostexViewScopeSpaceRef,
  type GhostexViewScopeState,
  type GhostexViewScopes,
} from './ghostex-settings/view-scopes';
export {
  WEB_LINK_OPEN_TARGET_OPTIONS,
  CHAT_FILE_OPEN_VIEW_OPTIONS,
  SIDEBAR_THEME_SETTING_OPTIONS,
  SESSION_CHAT_THEME_OPTIONS,
  DARK_THEME_PRESET_OPTIONS,
  LIGHT_THEME_PRESET_OPTIONS,
  APP_SHOTS_HOTKEY_OPTIONS,
  DEFAULT_EDITOR_COMMAND_OPTIONS,
  COMMANDS_PANEL_SIDE_OPTIONS,
  WINDOW_GLASS_OPTIONS,
  WINDOW_GLASS_SOURCE_OPTIONS,
  WINDOW_GLASS_IMAGE_PLACEMENT_OPTIONS,
  PANEL_ANIMATION_SPEED_OPTIONS,
  COMMANDS_PANEL_AUTO_MINIMIZE_DELAY_OPTIONS,
  SIDEBAR_SPACES_ENABLED_OPTIONS,
  SIDEBAR_SPACE_SWITCH_BEHAVIOR_OPTIONS,
  SIDEBAR_VISIBILITY_MEMORY_OPTIONS,
  PREFERRED_AGENT_INTERFACE_OPTIONS,
  PREFERRED_AGENT_INTERFACE_INHERIT_VALUE,
  getPreferredAgentInterfaceOverrideOptions,
  resolveEffectivePreferredAgentInterface,
  KEEP_AWAKE_DURATION_OPTIONS,
  AUTO_SLEEP_IDLE_MINUTE_OPTIONS,
  GHOSTTY_COPY_ON_SELECT_OPTIONS,
  GHOSTTY_CONFIRM_CLOSE_SURFACE_OPTIONS,
  GHOSTTY_SCROLLBAR_OPTIONS,
  PROMPT_EDITOR_BACKEND_OPTIONS,
  GHOSTTY_THEME_SETTING_OPTIONS,
  getGhosttyThemeSettingOptions,
} from './ghostex-settings/option-tables';
export {
  type RemoteMachineSettings,
  type RemoteMachineTransport,
  applyEnabledRemoteMachineOrder,
  isRemoteMachineEnabledInSidebar,
  normalizeRemoteMachineSettings,
} from './ghostex-settings/remote-machines';
export {
  normalizeTerminalDevServerIgnoredPortRuleInput,
  normalizeTerminalDevServerIgnoredPortRules,
} from './ghostex-settings/terminal-dev-servers';
export {
  SESSION_TITLE_GENERATION_AGENT_OPTIONS,
  SESSION_TITLE_GENERATION_PROMPT_PLACEHOLDER,
  getSessionTitleGenerationCommandPreview,
  isSessionTitleGenerationAgent,
} from './ghostex-settings/session-title-generation';
export {
  SETTINGS_MODAL_NAVIGATION_TABS,
  type SettingsModalNavigationTab,
  type SettingsModalNavigationState,
  DEFAULT_SETTINGS_MODAL_NAVIGATION_STATE,
  normalizeSettingsModalNavigationState,
} from './ghostex-settings/settings-modal-navigation';
export {
  normalizeghostexSettings,
  getTerminalFontFamilyForghostexSettings,
  applySidebarSettingsPreset,
  normalizeManageAdditionalDocsFolders,
  normalizeGlobalWorktreeCommand,
  normalizeGlobalBeadsDisplayKey,
  normalizeGlobalBeadsDirectory,
  normalizeGlobalDocsDirectory,
  getDefaultEditorCommandForSettings,
} from './ghostex-settings/normalize';
