/**
 * Writes the hotkey table the Rust Quick Access model reads, from the one TypeScript catalog.
 *
 *   bun tooling/gx-core/quick-access-hotkey-table.ts          # write it
 *   bun tooling/gx-core/quick-access-hotkey-table.ts --check  # exit 1 when it is stale
 *
 * CDXC:AppModal 2026-09-25 WHY:
 * `GHOSTEX_HOTKEY_DEFINITIONS` stays the single source (Settings and the CEF pages read it), so the
 * Rust copy is generated rather than hand-kept: a title, a default chord or an icon that drifted
 * would put a different Commands tab in front of the user with nothing to catch it. The icon is the
 * TypeScript `hotkeyActionIconName` itself, evaluated here, for the same reason.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { GHOSTEX_HOTKEY_DEFINITIONS } from '@/packages/shared/ghostex-hotkeys';
import { hotkeyActionIconName } from '@/tooling/gx-core/quick-access-icons';

const OUT = join(import.meta.dir, '../../packages/gx-core/src/quick_access/hotkey_table.rs');

const rust = (value: string) => JSON.stringify(value);
const list = (values: readonly string[] | undefined) => `&[${(values ?? []).map(rust).join(', ')}]`;

const rows = GHOSTEX_HOTKEY_DEFINITIONS.map(
  (definition) => `    HotkeyDefinition {
        id: ${rust(definition.id)},
        title: ${rust(definition.title)},
        description: ${rust(definition.description)},
        default_key: ${rust(definition.defaultKey)},
        windows_linux_default_key: ${definition.windowsLinuxDefaultKey === undefined ? 'None' : `Some(${rust(definition.windowsLinuxDefaultKey)})`},
        retired_default_keys: ${list(definition.retiredDefaultKeys)},
        kind: ${rust(definition.action.kind)},
        icon: ${rust(hotkeyActionIconName(definition.action))},
    },`
);

const text = `//! GENERATED by tooling/gx-core/quick-access-hotkey-table.ts from
//! packages/shared/ghostex-hotkeys.ts. Do not edit; run the generator.

/// One entry of \`GHOSTEX_HOTKEY_DEFINITIONS\`, with the Quick Access row icon already resolved.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub(crate) struct HotkeyDefinition {
    pub(crate) id: &'static str,
    pub(crate) title: &'static str,
    pub(crate) description: &'static str,
    pub(crate) default_key: &'static str,
    pub(crate) windows_linux_default_key: Option<&'static str>,
    pub(crate) retired_default_keys: &'static [&'static str],
    /// \`action.kind\`.
    pub(crate) kind: &'static str,
    /// \`hotkeyActionIconName(action)\`.
    pub(crate) icon: &'static str,
}

pub(crate) const HOTKEY_DEFINITIONS: &[HotkeyDefinition] = &[
${rows.join('\n')}
];
`;

if (process.argv.includes('--check')) {
  let current = '';
  try {
    current = readFileSync(OUT, 'utf8');
  } catch {}
  if (current !== text) {
    console.error(
      'packages/gx-core/src/quick_access/hotkey_table.rs is stale; run bun tooling/gx-core/quick-access-hotkey-table.ts'
    );
    process.exit(1);
  }
  console.log('hotkey table is current');
} else {
  writeFileSync(OUT, text);
  console.log(`wrote ${GHOSTEX_HOTKEY_DEFINITIONS.length} hotkey definitions`);
}
