// AUTO-GENERATED by scripts/generate-agent-paths.mjs
// Source of truth: gxserver-rs/src/paths.rs (AgentPaths)
// Do not edit manually; the Rust drift test will catch differences.

export const AGENTS_ROOT = ".agents" as const;
export const HOOKS_ROOT = ".ghostex/hooks" as const;
export const PROFILES_ROOT = ".agents/profiles" as const;
export const SKILLS_ROOT = ".agents/skills" as const;

export const AGENT_PATH_COMPONENTS = {
  agents_root: [".agents"],
  hooks_root: [".ghostex","hooks"],
  profiles_root: [".agents","profiles"],
  skills_root: [".agents","skills"],
} as const;
